// swift-tools-version:5.5
import PackageDescription

let package = Package(
    name: "MediaEditor",
    platforms: [
        .macOS(.v11)
    ],
    products: [
        .executable(name: "mec", targets: ["mec"])
    ],
    targets: [
        .target(
            name: "BaseUtils",
            path: "imgui/addon/BaseUtils",
            sources: [
                "Src/CpuUtils.cpp",
                "Src/FileSystemUtils.cpp",
                "Src/Logger.cpp",
                "Src/SimdOpt.cpp",
                "Src/ThreadUtils.cpp",
                "Src/TimeUtils.cpp"
            ],
            publicHeadersPath: "Include",
            cxxSettings: [
                .headerSearchPath("Include"),
                .define("BaseUtils_STATIC", to: "1")
            ]
        ),
        .target(
            name: "ImMaskCreator",
            dependencies: ["BaseUtils"],
            path: "imgui/addon/ImMaskCreator",
            sources: [
                "Src/BoxFilter.cpp",
                "Src/Contour2Mask.cpp",
                "Src/ImMaskCreatorImpl.cpp",
                "Src/MatFilter.cpp",
                "Src/MatIo.cpp",
                "Src/MatMath.cpp",
                "Src/Morph.cpp"
            ],
            publicHeadersPath: "Include",
            cxxSettings: [
                .headerSearchPath("Include"),
                .headerSearchPath("../BaseUtils/Include"),
                .headerSearchPath("../.."), // For imgui.h
                .headerSearchPath("../../misc"), // For stb_image.h
                .headerSearchPath("../../misc/json"), // For imgui_json.h
                .headerSearchPath("../ImNewCurve"), // For ImNewCurve.h
                .define("ImMaskCreator_STATIC", to: "1"),
                .define("ImMaskCreator_VERSION_MAJOR", to: "1"),
                .define("ImMaskCreator_VERSION_MINOR", to: "0"),
                .define("ImMaskCreator_VERSION_PATCH", to: "0"),
                .define("ImMaskCreator_VERSION_BUILD", to: "0")
            ]
        ),
        .target(
            name: "dearimgui",
            dependencies: ["BaseUtils"],
            path: "imgui",
            sources: [
                "imgui.cpp",
                "imgui_draw.cpp",
                "imgui_widgets.cpp",
                "imgui_tables.cpp",
                "imgui_texture.cpp",
                "imgui_texture_metal.mm",
                "imgui_helper.cpp",
                "immat.cpp",
                "misc/cpp/codewin.cpp",
                "misc/cpp/imgui_stdlib.cpp",
                "misc/cpp/dir_iterate.cpp",
                "misc/cpp/imgui_cpu.cpp",
                "misc/cpp/imgui_fft.cpp",
                "misc/cpp/imgui_socket.cpp",
                "misc/json/imgui_json.cpp",
                "backends/imgui_impl_osx.mm",
                "backends/imgui_impl_metal.mm",
                "fonts/mono_weihei.cpp",
                "fonts/mono_narrow.cpp",
                "addon/ImGuiFileDialog/ImGuiFileDialog.cpp",
                "addon/implot/implot.cpp",
                "addon/implot/implot_items.cpp",
                "addon/TextEditor/TextEditor.cpp",
                "addon/imgui_extra_widget/imgui_extra_widget.cpp",
                "addon/imgui_extra_widget/imgui_extra_spinner.cpp",
                "addon/ImCurve/imgui_curve.cpp",
                "addon/ImCurve/imgui_spline.cpp",
                "addon/ImNewCurve/ImNewCurve.cpp",
                "addon/ImGuiTabWindow/ImGuiTabWindow.cpp",
                "addon/node_editor/imgui_canvas.cpp",
                "addon/node_editor/imgui_node_editor_api.cpp",
                "addon/node_editor/imgui_node_editor.cpp",
                "addon/ImGuiZmoQuat/ImGuiZMOquat.cpp",
                "addon/ImGuiZmo/ImGuiOrient.cpp",
                "addon/ImGuiZmo/ImGuiZmo.cpp",
                "addon/ImGuiZmo/model.cpp",
                "addon/imgui_toggle/imgui_toggle.cpp",
                "addon/imgui_toggle/imgui_toggle_palette.cpp",
                "addon/imgui_toggle/imgui_toggle_presets.cpp",
                "addon/imgui_toggle/imgui_toggle_renderer.cpp",
                "addon/imgui_tex_inspect/imgui_tex_inspect.cpp",
                "addon/ImCoolbar/ImCoolbar.cpp",
                "addon/ImGuiStyleSerializer/ImGuiStyleSerializer.cpp",
                "icons/icons.cpp",
                "icons/folder.cpp",
                "icons/fontaudio.cpp",
                "icons/fa_brands.cpp",
                "icons/fa_regular.cpp",
                "icons/fa_solid.cpp",
                "icons/webfont.cpp",
                "icons/fork_webfont.cpp",
                "icons/material_icons.cpp",
                "icons/kenney.cpp",
                "icons/StepMath.cpp",
                "icons/Code.cpp",
                "icons/lucide.cpp"
            ],
            publicHeadersPath: ".",
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("backends"),
                .headerSearchPath("addon/BaseUtils/Include"),
                .headerSearchPath("misc"),
                .headerSearchPath("misc/cpp"),
                .headerSearchPath("misc/json"),
                .headerSearchPath("icons"),
                .headerSearchPath("addon/ImGuiFileDialog"),
                .headerSearchPath("addon/implot"),
                .headerSearchPath("addon/TextEditor"),
                .headerSearchPath("addon/imgui_extra_widget"),
                .headerSearchPath("addon/ImCurve"),
                .headerSearchPath("addon/ImNewCurve"),
                .headerSearchPath("addon/ImGuiTabWindow"),
                .headerSearchPath("addon/node_editor"),
                .headerSearchPath("addon/ImGuiZmoQuat"),
                .headerSearchPath("addon/ImGuiZmo"),
                .headerSearchPath("addon/imgui_toggle"),
                .headerSearchPath("addon/imgui_tex_inspect"),
                .headerSearchPath("addon/ImCoolbar"),
                .headerSearchPath("addon/ImGuiStyleSerializer"),
                .define("IMGUI_RENDERING_MATAL", to: "1"),
                .define("IMGUI_FONT_WEIHEI", to: "1"),
                .define("IMGUI_FONT_MONONARROW", to: "1"),
                .define("IMGUI_ICONS", to: "1"),
                .define("IMGUI_USER_CONFIG", to: "\"imconfig.h\"")
            ]
        ),
        .target(
            name: "BluePrintSDK",
            dependencies: ["dearimgui"],
            path: "blueprintsdk",
            sources: [
                "src/BluePrint.cpp",
                "src/Context.cpp",
                "src/Pin.cpp",
                "src/Node.cpp",
                "src/Icon.cpp",
                "src/Debug.cpp",
                "src/Utils.cpp",
                "src/Document.cpp",
                "src/UI.cpp"
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../imgui"),
                .headerSearchPath("../imgui/misc"),
                .headerSearchPath("../imgui/misc/json"),
                .headerSearchPath("../imgui/misc/cpp"),
                .headerSearchPath("../imgui/icons"),
                .headerSearchPath("../imgui/addon/ImGuiFileDialog"),
                .headerSearchPath("../imgui/addon/implot"),
                .headerSearchPath("../imgui/addon/TextEditor"),
                .headerSearchPath("../imgui/addon/imgui_extra_widget"),
                .headerSearchPath("../imgui/addon/ImCurve"),
                .headerSearchPath("../imgui/addon/ImNewCurve"),
                .headerSearchPath("../imgui/addon/ImGuiTabWindow"),
                .headerSearchPath("../imgui/addon/node_editor"),
                .headerSearchPath("../imgui/addon/ImGuiZmoQuat"),
                .headerSearchPath("../imgui/addon/ImGuiZmo"),
                .headerSearchPath("../imgui/addon/imgui_toggle"),
                .headerSearchPath("../imgui/addon/imgui_tex_inspect"),
                .headerSearchPath("../imgui/addon/ImCoolbar"),
                .headerSearchPath("../imgui/addon/ImGuiStyleSerializer"),
                .headerSearchPath("src/BuildInNodes"),
                .headerSearchPath("src/BuildInNodes/CommonNode"),
                .headerSearchPath("src/BuildInNodes/SystemNode")
            ]
        ),
        .target(
            name: "MediaCore",
            dependencies: ["dearimgui", "BaseUtils", "ImMaskCreator"],
            path: "MediaCore",
            sources: [
                "src/AudioClip.cpp",
                "src/AudioEffectFilter_FFImpl.cpp",
                "src/AudioRender_Impl_Sdl2.cpp",
                "src/AudioTrack.cpp",
                "src/DebugHelper.cpp",
                "src/FFUtils.cpp",
                "src/FontDescriptor.cpp",
                "src/FontManager_Fontconfig.cpp",
                "src/HwaccelManager.cpp",
                "src/ImageSequenceReader.cpp",
                "src/MatUtils.cpp",
                "src/MediaCore.cpp",
                "src/MediaData.cpp",
                "src/MediaEncoder.cpp",
                "src/MediaParser.cpp",
                "src/MediaReader.cpp",
                "src/MultiTrackAudioReader.cpp",
                "src/MultiTrackVideoReader.cpp",
                "src/Overview.cpp",
                "src/SharedSettings.cpp",
                "src/SingleTrackVideoReader.cpp",
                "src/Snapshot.cpp",
                "src/SubtitleClip_AssImpl.cpp",
                "src/SubtitleTrack_AssImpl.cpp",
                "src/SubtitleTrack.cpp",
                "src/TextureManager.cpp",
                "src/VideoBlender.cpp",
                "src/VideoClip.cpp",
                "src/VideoReader.cpp",
                "src/VideoTrack.cpp",
                "src/VideoTransformFilter_FFImpl.cpp",
                "src/VideoTransformFilter_VkImpl.cpp",
                "src/VideoTransformFilter.cpp"
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../imgui"),
                .headerSearchPath("../imgui/misc"),
                .headerSearchPath("../imgui/misc/json"),
                .headerSearchPath("../imgui/misc/cpp"),
                .headerSearchPath("../imgui/icons"),
                .headerSearchPath("../imgui/addon/BaseUtils/Include"),
                .headerSearchPath("../imgui/addon/ImMaskCreator/Include"),
                .headerSearchPath("../imgui/addon/ImGuiFileDialog"),
                .headerSearchPath("../imgui/addon/implot"),
                .headerSearchPath("../imgui/addon/TextEditor"),
                .headerSearchPath("../imgui/addon/imgui_extra_widget"),
                .headerSearchPath("../imgui/addon/ImCurve"),
                .headerSearchPath("../imgui/addon/ImNewCurve"),
                .headerSearchPath("../imgui/addon/ImGuiTabWindow"),
                .headerSearchPath("../imgui/addon/node_editor"),
                .headerSearchPath("../imgui/addon/ImGuiZmoQuat"),
                .headerSearchPath("../imgui/addon/ImGuiZmo"),
                .headerSearchPath("../imgui/addon/imgui_toggle"),
                .headerSearchPath("../imgui/addon/imgui_tex_inspect"),
                .headerSearchPath("../imgui/addon/ImCoolbar"),
                .headerSearchPath("../imgui/addon/ImGuiStyleSerializer"),
                .unsafeFlags(["-I/opt/homebrew/include", "-I/opt/homebrew/include/SDL2"]),
                .define("MEDIACORE_VERSION_MAJOR", to: "1"),
                .define("MEDIACORE_VERSION_MINOR", to: "12"),
                .define("MEDIACORE_VERSION_PATCH", to: "25"),
                .define("MEDIACORE_VERSION_BUILD", to: "260629")
            ]
        ),
        .executableTarget(
            name: "mec",
            dependencies: [
                "MediaCore",
                "BluePrintSDK",
                "dearimgui",
                "ImMaskCreator",
                "BaseUtils"
            ],
            path: ".",
            sources: [
                "MediaEditor.cpp",
                "MediaTimeline.cpp",
                "MecProject.cpp",
                "Event.cpp",
                "EventStackFilter.cpp",
                "MediaPlayer.cpp",
                "BackgroundTask.cpp",
                "BgtaskSceneDetect.cpp",
                "BgtaskVidstab.cpp",
                "VideoTransformFilterUiCtrl.cpp",
                "entry_metal.mm"
            ],
            cxxSettings: [
                .headerSearchPath("imgui"),
                .headerSearchPath("imgui/backends"),
                .headerSearchPath("imgui/misc"),
                .headerSearchPath("imgui/misc/cpp"),
                .headerSearchPath("imgui/misc/json"),
                .headerSearchPath("imgui/icons"),
                .headerSearchPath("imgui/addon/BaseUtils/Include"),
                .headerSearchPath("imgui/addon/ImMaskCreator/Include"),
                .headerSearchPath("imgui/addon/ImGuiFileDialog"),
                .headerSearchPath("imgui/addon/implot"),
                .headerSearchPath("imgui/addon/TextEditor"),
                .headerSearchPath("imgui/addon/imgui_extra_widget"),
                .headerSearchPath("imgui/addon/ImCurve"),
                .headerSearchPath("imgui/addon/ImNewCurve"),
                .headerSearchPath("imgui/addon/ImGuiTabWindow"),
                .headerSearchPath("imgui/addon/node_editor"),
                .headerSearchPath("imgui/addon/ImGuiZmoQuat"),
                .headerSearchPath("imgui/addon/ImGuiZmo"),
                .headerSearchPath("imgui/addon/imgui_toggle"),
                .headerSearchPath("imgui/addon/imgui_tex_inspect"),
                .headerSearchPath("imgui/addon/ImCoolbar"),
                .headerSearchPath("imgui/addon/ImGuiStyleSerializer"),
                .headerSearchPath("blueprintsdk/include"),
                .headerSearchPath("MediaCore/include"),
                .headerSearchPath("imgui/apps/application/include"),
                .unsafeFlags(["-I/opt/homebrew/include", "-I/opt/homebrew/include/SDL2"]),
                .define("MEDIAEDITOR_VERSION_MAJOR", to: "0"),
                .define("MEDIAEDITOR_VERSION_MINOR", to: "9"),
                .define("MEDIAEDITOR_VERSION_PATCH", to: "9"),
                .define("MEDIAEDITOR_VERSION_BUILD", to: "260629"),
                .define("APP_NAME", to: "\"mec\"")
            ],
            linkerSettings: [
                .unsafeFlags(["-L/opt/homebrew/lib"]),
                .linkedLibrary("avcodec"),
                .linkedLibrary("avformat"),
                .linkedLibrary("avutil"),
                .linkedLibrary("swresample"),
                .linkedLibrary("avfilter"),
                .linkedLibrary("swscale"),
                .linkedLibrary("avdevice"),
                .linkedLibrary("ass"),
                .linkedLibrary("fontconfig"),
                .linkedLibrary("SDL2"),
                .linkedLibrary("crypto"),
                .linkedLibrary("ssl"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Cocoa"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("GameController")
            ]
        )
    ],
    cLanguageStandard: .c11,
    cxxLanguageStandard: .cxx17
)
